### ISSUE TITLE
Concoct in binning.md tutorial: how to run multi-threaded?

### ISSUE THREAD

**Issue by FMKerckhof** [chrisquince/Ebame3#1]
Dear Christopher,

I had the pleasure some weeks ago to follow your training at the EBAME3 workshop. Now,
I am trying to replicate the analysis on my own server (Ubuntu server 16.04.3 LTS, 24 cores) with my own data. I was going through `Binning.md` tutorial and found that you suggested to run concoct with multiple threads (`-t 12`):
`concoct --coverage_file Coverage.tsv --composition_file ../Assembly/final_contigs_c10K.fa -t 12 `. I have now concoct 0.4.0 (latest stable release: https://github.com/BinPro/CONCOCT/releases), but in the current documentation has no option` -t` and when I run it that option is not recognized. Am I using the wrong version here? Or is there a special way to compile concoct/gsl to allow multi-threading?

Kind regards,

Frederiek - Maarten Kerckhof

**Comment by chrisquince** [comment]
Dear Frederiek,

Currently this is available only in a development branch of concoct. It will be released soon, however. Can you check out and install this branch:

experimental_cleanup_cconcoct

Thanks,
Chris
